apiVersion: v1
kind: ConfigMap
metadata:
  name: myweb-nginx-config
  namespace: myweb
data:
  default.conf: |-
    server {
        listen 80;
        server_name _;  # catch-all for internal traffic

        location / {
            proxy_pass http://myweb-app:8000;

            # Forward headers for Django
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }