apiVersion: v1
kind: Secret
metadata:
  name: myweb-env
  namespace: myweb
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  # Database
  MYSQL_DATABASE: "mysite_db"
  MYSQL_USER: "mysite_user"
  MYSQL_PASSWORD: "mysite_pass"       # critical: replace
  MYSQL_ROOT_PASSWORD: "rootpass"     # critical: replace

  # Web / Django
  DJANGO_ENV: "prod"
  DB_HOST: "myweb-db"
  DB_PORT: "3306"

  EMAIL_HOST_EMAIL: "admin@admin.com" # critical: replace
  EMAIL_HOST_PASSWORD: "P@ssw0rd"     # critical: replace

  # Container names
  DB_CONTAINER_NAME: "myweb-db"
  WEB_CONTAINER_NAME: "myweb-app"
  NGINX_CONTAINER_NAME: "myweb-nginx"